table 'Pricing Comparison'
	lineageTag: e5fcac25-60b8-46bf-beef-85e54cd44b40

	measure count_e1_2 = CALCULATE(COUNTROWS('Pricing Comparison'),'Pricing Comparison'[diff_e1_2] < -0.00)
		formatString: #,0
		lineageTag: 32f2be34-01f9-4bc8-9dfb-53a79a0ab6e3

	measure vol_e1_2 = CALCULATE(SUM('Pricing Comparison'[diff_e1_2]),'Pricing Comparison'[diff_e1_2] < -0.00)
		formatString: #,0%;-#,0%;#,0%
		lineageTag: a5f35c20-a4eb-4eac-81af-4f7c340f19a9

	measure count_m1_2 = CALCULATE(COUNTROWS('Pricing Comparison'),'Pricing Comparison'[diff_m1_2] < -0.00)
		formatString: #,0
		lineageTag: bc6ff760-ff2b-4e5a-bb4a-e761c87d5375

	measure count_v1_2 = CALCULATE(COUNTROWS('Pricing Comparison'),'Pricing Comparison'[diff_v1_2] < -0.00)
		formatString: #,0
		lineageTag: c0bc85a0-47ce-42d3-a320-177226774aaf

	measure vol_m1_2 = CALCULATE(SUM('Pricing Comparison'[diff_m1_2]),'Pricing Comparison'[diff_m1_2] < -0.00)
		formatString: #,0%;-#,0%;#,0%
		lineageTag: bb54c2a0-e401-4309-9c1b-de4cdf2437bf

	measure vol_v1_2 = CALCULATE(SUM('Pricing Comparison'[diff_v1_2]),'Pricing Comparison'[diff_v1_2] < -0.00)
		formatString: #,0%;-#,0%;#,0%
		lineageTag: c4114518-6c09-4058-b0e2-7c53e9d773e7

	measure count_any = CALCULATE(COUNTROWS('Pricing Comparison'),'Pricing Comparison'[diff_min] < -0.00)
		formatString: #,0
		lineageTag: 845f7fd0-32cd-4352-bcd6-2c92eaef1170

	measure count_pa = CALCULATE(COUNTROWS('Pricing Comparison'),'Pricing Comparison'[diff_pa] < -0.00)
		formatString: #,0
		lineageTag: 8dea5f21-f0c5-471b-aa2c-cff10410cdbc

	measure vol_pa = CALCULATE(SUM('Pricing Comparison'[diff_pa]),'Pricing Comparison'[diff_pa] < -0.00)
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 89f5e60c-afb5-4e4b-a4d3-47713b11ee64

	column gmax_runner_sharecode
		dataType: string
		lineageTag: 94ed0da9-cbc2-43e5-8b8f-30ee54c7e621
		summarizeBy: none
		sourceColumn: gmax_runner_sharecode

		annotation SummarizationSetBy = Automatic

	column gmax_race_sharecode
		dataType: string
		lineageTag: dc685318-b1aa-4cfd-9a52-e116f53e51c6
		summarizeBy: none
		sourceColumn: gmax_race_sharecode

		annotation SummarizationSetBy = Automatic

	column price_time
		dataType: dateTime
		formatString: yyyy-mm-dd h:nn:ss
		lineageTag: c9e45e8d-50e8-42cd-ade1-ed21036c59ef
		summarizeBy: none
		sourceColumn: price_time

		variation Variation
			isDefault
			relationship: b18e25be-a6b2-4a69-9848-efa3995cca2e
			defaultHierarchy: LocalDateTable_20162817-6765-433e-89c5-7f003b9a2c8c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column price_m1_2
		dataType: double
		formatString: 0.00
		lineageTag: 0a721846-b215-40dd-8cb5-2d173e5cc7bd
		summarizeBy: sum
		sourceColumn: price_m1_2

		annotation SummarizationSetBy = Automatic

	column price_e1_2
		dataType: double
		formatString: 0.00
		lineageTag: d06f54ec-0909-491b-8466-84c6688972e2
		summarizeBy: sum
		sourceColumn: price_e1_2

		annotation SummarizationSetBy = Automatic

	column price_v1_2
		dataType: double
		formatString: 0.00
		lineageTag: e94af241-2a69-4088-a44e-eab6340652ca
		summarizeBy: sum
		sourceColumn: price_v1_2

		annotation SummarizationSetBy = Automatic

	column price_betfair
		dataType: double
		lineageTag: 5b17253a-b3a5-4cb9-9f9e-8a456e088a58
		summarizeBy: sum
		sourceColumn: price_betfair

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column diff_v1_2
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 72ffeae4-e24b-441b-87e2-f8d1aff419d1
		summarizeBy: sum
		sourceColumn: diff_v1_2

		annotation SummarizationSetBy = Automatic

	column diff_m1_2
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 0da50a9b-66fc-40b8-b67b-29f7fad581d1
		summarizeBy: sum
		sourceColumn: diff_m1_2

		annotation SummarizationSetBy = Automatic

	column diff_e1_2
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 20a66f9f-9871-41d0-9b5c-888ae5c0e0dc
		summarizeBy: sum
		sourceColumn: diff_e1_2

		annotation SummarizationSetBy = Automatic

	column price_pa
		dataType: double
		lineageTag: 42bcbefb-4a16-4828-841b-7250c7c35fc7
		summarizeBy: sum
		sourceColumn: price_pa

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column diff_pa
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c45e37a8-c101-4ca8-bb3d-44d432a0dd08
		summarizeBy: sum
		sourceColumn: diff_pa

		annotation SummarizationSetBy = Automatic

	column diff_min
		dataType: double
		lineageTag: bf6ac0b1-abbd-4582-900e-e32c1482b8a6
		summarizeBy: sum
		sourceColumn: diff_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Pricing Comparison' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("general-mariadb-1-read.cqqnayulzicg.eu-west-2.rds.amazonaws.com", "general", [ReturnSingleDatabase=true, Query="select * from general.pricing_arbitrage_price; ", CreateNavigationProperties=false])
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

