table 'TPD Race'
	lineageTag: 918a3b93-b8a2-4b75-84c6-422198f93069
	sourceLineageTag: d532d7ad-71cf-4312-ac51-6f6f6c4aebd8

	measure 'Race Published' = EXTERNALMEASURE("Race Published", INTEGER, "DirectQuery to AS - _source")
		formatString: #,0
		lineageTag: 3725f289-a8a7-40f7-95fa-92ff95bdfe58
		sourceLineageTag: 7b4da8d7-e1d5-4f23-bffe-c43d0e0184cf
		dataCategory: Uncategorized

	measure 'Race Total' = EXTERNALMEASURE("Race Total", INTEGER, "DirectQuery to AS - _source")
		formatString: #,0
		lineageTag: 70105867-bb20-4912-bdc8-9d724cbbd057
		sourceLineageTag: cce74ba4-7477-4a99-9864-607e50eed92a
		dataCategory: Uncategorized

	measure 'Race Unpublished' = EXTERNALMEASURE("Race Unpublished", INTEGER, "DirectQuery to AS - _source")
		formatString: #,0
		lineageTag: d244b16a-f64f-48f9-aa85-31a8ad0049c4
		sourceLineageTag: 8f2f9f3b-b997-4e16-b3e6-4b3fdd9aacdf
		dataCategory: Uncategorized

	measure 'First Post Time' = EXTERNALMEASURE("First Post Time", DATETIME, "DirectQuery to AS - _source")
		formatString: yyyy\-mm\-dd hh:nn:ss
		lineageTag: 0bf61198-276a-433a-aae8-9647d9b36fab
		sourceLineageTag: 4385ca87-cae7-439a-8cfd-bb5903e752ea
		dataCategory: Uncategorized

	measure 'Jump Fluncy A%' = EXTERNALMEASURE("Jump Fluncy A%", DOUBLE, "DirectQuery to AS - _source")
		formatString: 0%;-0%;0%
		lineageTag: 4b0475c7-4bb5-4909-8bf2-860bd7ac3ebf
		sourceLineageTag: 25061749-248d-4a60-aa72-41ce844eb105
		dataCategory: Uncategorized

	column 'TPD Race ID'
		dataType: int64
		isNullable: false
		formatString: 0
		lineageTag: 59bdfc8c-e8c4-4496-b5e4-666728d43260
		sourceLineageTag: 08cd8325-e878-444f-b3e5-c60f2be90666
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: TPD Race ID

		annotation SummarizationSetBy = User

	column 'TPD Meeting ID'
		dataType: int64
		formatString: 0
		lineageTag: 797f3d22-e269-478e-9f30-800bb4907ff5
		sourceLineageTag: df99b243-db49-4770-ad39-8ed361d8c8c4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: TPD Meeting ID

		annotation SummarizationSetBy = User

	column 'Post Time'
		dataType: dateTime
		formatString: yyyy\-mm\-dd hh:nn:ss
		lineageTag: f1a0e062-961f-449e-ba38-726a9bc637d1
		sourceLineageTag: d26f2bab-466f-4233-a665-9eff251ccc11
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Post Time

		variation Variation
			isDefault
			relationship: fa6f0638-5988-462b-8f7b-2508b00418fe
			defaultHierarchy: LocalDateTable_01981014-986b-4d10-a6f6-92650cdd4519.'Date Hierarchy'

		annotation SummarizationSetBy = User

	column 'Race Number'
		dataType: int64
		formatString: 0
		lineageTag: 7ff660c5-5d2d-4901-81c1-5377e30056c1
		sourceLineageTag: 553a2745-9073-4223-8aac-61d85610ff70
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Race Number

		annotation SummarizationSetBy = User

	column 'Race Length'
		dataType: string
		lineageTag: 47476506-89d0-462c-a77f-cf64100d36a9
		sourceLineageTag: b0e57329-e995-456b-9664-ee6ea984b755
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Race Length

		annotation SummarizationSetBy = User

	column 'Race Length (Meter)'
		dataType: double
		lineageTag: eaa10d2a-59b1-416f-8018-557d5bf4b14e
		sourceLineageTag: ed9a67c9-867a-41c7-b4e4-40e1d218c676
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Race Length (Meter)

		annotation SummarizationSetBy = User

	column Surface
		dataType: string
		lineageTag: b85f5d55-71df-492a-befb-ba60db06c675
		sourceLineageTag: 1ccea177-48d5-4c58-91d8-6db4a2a8a25b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Surface

		annotation SummarizationSetBy = User

	column Obstacle
		dataType: string
		lineageTag: 881cce44-2c4b-4f7b-ba96-74eef1232f2c
		sourceLineageTag: 68454e3e-c4b1-4f5e-bc88-e7a2ab0527b7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Obstacle

		annotation SummarizationSetBy = User

	column Going
		dataType: string
		lineageTag: 3b3e2c29-fb15-4a7b-9d15-043090816f74
		sourceLineageTag: dbe8ae54-5bdf-4510-9f82-7a9fc0ac774f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Going

		annotation SummarizationSetBy = User

	column 'Going Number'
		dataType: double
		lineageTag: 95d3d388-b991-4206-86ae-a550bc146bce
		sourceLineageTag: 8d55d3fa-4e88-47e3-9b6b-cfaf0d20974e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Going Number

		annotation SummarizationSetBy = User

	column Handicap
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 51da4b77-565c-45c2-bdf8-eb5b60c20ffa
		sourceLineageTag: 99058c62-4e4b-40d3-8b26-0bd38af062fd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Handicap

		annotation SummarizationSetBy = User

	column 'Race Class'
		dataType: string
		lineageTag: 4862b25c-bddf-4081-89ae-5d80ff11f940
		sourceLineageTag: 8697005a-83bf-47f1-9507-a968a49cf552
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Race Class

		annotation SummarizationSetBy = User

	column 'Win Time'
		dataType: double
		lineageTag: c0ccd0a7-2d33-45f7-8edb-3f11cfa1e58c
		sourceLineageTag: 8c371251-1121-4cc1-a5b9-f5434d9c1f27
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Win Time

		annotation SummarizationSetBy = User

	column 'Race Status'
		dataType: string
		lineageTag: 022c561d-8f4f-415d-b863-f92814999d8c
		sourceLineageTag: 2cbd9de0-a7fc-4881-b403-d1ceec3171d0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Race Status

		annotation SummarizationSetBy = User

	column 'Race Tracked'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 27c1d904-ab5e-4478-988c-8a8bde5efa68
		sourceLineageTag: 536bbb40-6d0b-49b8-b575-2eb13a7d032f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Race Tracked

		annotation SummarizationSetBy = User

	column 'Published Status'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fbab72c3-dd2d-4bfd-ab2e-ec1d106f2cdc
		sourceLineageTag: a9071709-4353-4910-b53e-ff78a143d6d6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Published Status

		annotation SummarizationSetBy = User

	column 'Gmax Race Sharecode'
		dataType: string
		lineageTag: 6ab91a91-409d-415b-8420-aceb41d3f638
		sourceLineageTag: 7cbb4d4e-d75b-422f-85f0-7d9355c71457
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Gmax Race Sharecode

		annotation SummarizationSetBy = User

	column 'Gmax Race Estimated'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 905342d5-3a91-4032-bf32-a8a273bd37f3
		sourceLineageTag: 1859bc4e-fe48-47bd-9404-bf2aea3136d1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Gmax Race Estimated

		annotation SummarizationSetBy = User

	column 'Race Title'
		dataType: string
		lineageTag: 6de951d7-055d-4e92-a29c-9b7e552b46fe
		sourceLineageTag: 4190a9d9-0504-43fd-981b-edaa8d727b8e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Race Title

		annotation SummarizationSetBy = User

	column 'Race Group'
		dataType: string
		lineageTag: 8c1f26f3-fdb0-451e-b060-a32bf83651b5
		sourceLineageTag: 8793c2aa-4c18-4b4d-98df-c350200cb276
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Race Group

		annotation SummarizationSetBy = User

	column 'Race Grade'
		dataType: string
		lineageTag: d1245ffd-d2e8-45a5-88b7-ef7ec76eb29a
		sourceLineageTag: 41315256-4b6d-4ca7-bc43-87c24da69e04
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Race Grade

		annotation SummarizationSetBy = User

	column 'Number of Runners'
		dataType: int64
		formatString: 0
		lineageTag: 9732c477-0f3a-4e6c-911c-9bccb9cf5167
		sourceLineageTag: f25716b4-0c57-43d8-8623-a5613e94f7f1
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Number of Runners

		annotation SummarizationSetBy = User

	column 'Horse Eligibility'
		dataType: string
		lineageTag: 79fc9673-fdbc-4efd-b6f2-50e52becb759
		sourceLineageTag: 3ef2cc7a-9492-401f-b9e4-0dfe273c0d31
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Horse Eligibility

		annotation SummarizationSetBy = User

	column Weather
		dataType: string
		lineageTag: aed17a0c-d85f-416d-862d-1b67168ce4df
		sourceLineageTag: cddaf959-24a8-4690-87e6-32b66c12aa78
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Weather

		annotation SummarizationSetBy = User

	column 'Total Prizes'
		dataType: int64
		formatString: 0
		lineageTag: 9f9a5763-9c65-469c-8fc3-b3ecff92514b
		sourceLineageTag: d862b155-721c-44d0-98a6-e2d1d220f692
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Total Prizes

		annotation SummarizationSetBy = User

	partition 'TPD Race' = entity
		mode: directQuery
		source
			entityName: TPD Race
			expressionSource: 'DirectQuery to AS - _source'

	annotation PBI_ResultType = Exception

