table 'TPD Runner'
	lineageTag: 46c2c1cd-fa22-4b5f-9b13-44f5017cc3a4
	sourceLineageTag: 7f52b5ff-a342-4767-98f2-41214dbc6054

	measure 'Horse Entered' = EXTERNALMEASURE("Horse Entered", INTEGER, "DirectQuery to AS - _source")
		formatString: #,0
		lineageTag: 6f73c5bb-87ec-41cb-ab83-e189a05af7a4
		sourceLineageTag: 2f6cb432-3c02-433f-ba3e-6217fe5ac173
		dataCategory: Uncategorized

	measure 'Horse Finished' = EXTERNALMEASURE("Horse Finished", INTEGER, "DirectQuery to AS - _source")
		formatString: #,0
		lineageTag: e8607c81-c075-4227-a715-97d432e90af5
		sourceLineageTag: bdf11e82-149c-4b51-95e5-bd9c5ec07814
		dataCategory: Uncategorized

	measure 'Horse Tracked' = EXTERNALMEASURE("Horse Tracked", INTEGER, "DirectQuery to AS - _source")
		formatString: #,0
		lineageTag: 43d2262b-e4f3-48d6-8327-f8279a469a1c
		sourceLineageTag: 27c028d4-6b30-4462-a6f5-3052f0bcdf97
		dataCategory: Uncategorized

	column 'TPD Runner ID'
		dataType: int64
		isNullable: false
		formatString: 0
		lineageTag: bdcb8eab-f4e4-4e50-a88f-5b9e38a5a06e
		sourceLineageTag: ae5924ee-49fe-4ee8-96a0-2799d85f8fa9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: TPD Runner ID

		annotation SummarizationSetBy = User

	column 'TPD Race ID'
		dataType: int64
		formatString: 0
		lineageTag: cac3a419-a7d9-491a-b168-faa5c76f1f52
		sourceLineageTag: cc5da9ee-ea1c-43c6-8d46-c44f248eedae
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: TPD Race ID

		annotation SummarizationSetBy = User

	column 'Runner Number'
		dataType: string
		lineageTag: d066268b-6c47-4b3a-9691-8b075cf02545
		sourceLineageTag: 1c07b0ea-40b4-419a-bce8-8caa198d1d9d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Runner Number

		annotation SummarizationSetBy = User

	column 'Finish Position'
		dataType: int64
		formatString: 0
		lineageTag: 05e14e1c-8da3-4bad-859c-16ae517abc42
		sourceLineageTag: 889a70e6-bf11-4978-9257-b7d4ea568e3d
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Finish Position

		annotation SummarizationSetBy = User

	column 'Finish Time'
		dataType: double
		lineageTag: 9a771c0f-5d6d-45cd-9c21-8b2852e65be2
		sourceLineageTag: e90f97dd-321b-44ba-95be-c30e80ef1d24
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Finish Time

		annotation SummarizationSetBy = User

	column 'Stride Length'
		dataType: double
		lineageTag: fcd9c381-9c4d-462b-a49a-c276b93450f5
		sourceLineageTag: ccd823a9-1ba8-462a-bace-3971c5768131
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Stride Length

		annotation SummarizationSetBy = User

	column 'Stride Frequency'
		dataType: double
		lineageTag: 5e224599-a6f6-4184-8697-a46625956fbe
		sourceLineageTag: 04086215-7c13-4614-b74f-ac7c19f4b111
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Stride Frequency

		annotation SummarizationSetBy = User

	column 'PA Horse ID'
		dataType: int64
		formatString: 0
		lineageTag: 7f5a38df-f59a-4e3d-8cad-62ce170bf1e4
		sourceLineageTag: 701303dd-b49f-42fc-8d2f-4e9b7d8161b7
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: PA Horse ID

		annotation SummarizationSetBy = User

	column 'Horse Name'
		dataType: string
		lineageTag: b0a1411e-608d-49fe-b66e-c54339b42c5b
		sourceLineageTag: b04367d2-8c95-4dde-a0c2-e166d602b1b2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Horse Name

		annotation SummarizationSetBy = User

	column 'Horse Age'
		dataType: int64
		formatString: 0
		lineageTag: 2508cc04-e58f-448a-a614-5e795dd819be
		sourceLineageTag: b2078064-65b3-49fb-a72f-54c50dd796a7
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Horse Age

		annotation SummarizationSetBy = User

	column 'Runner Status'
		dataType: string
		lineageTag: df53c909-4df5-488e-97c7-2b82cf0f08e1
		sourceLineageTag: 4a89dbc9-c830-4a3f-acfb-96e2f02d8a83
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Runner Status

		annotation SummarizationSetBy = User

	column 'Gmax Runner Sharecode'
		dataType: string
		lineageTag: fd8c711a-f0b0-485f-a387-d031b3ba59ea
		sourceLineageTag: 880ff6b9-18ca-40b2-ad46-40dd8bdf6ecd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Gmax Runner Sharecode

		annotation SummarizationSetBy = User

	column 'Tracker Used'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1a2c79df-2253-4746-bdef-f220afe85993
		sourceLineageTag: dbb0863c-656f-47b3-a068-192ee3ccc99e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Tracker Used

		annotation SummarizationSetBy = User

	column Velocity
		dataType: double
		lineageTag: 88fe104b-888a-44b1-9107-2298342de8ab
		sourceLineageTag: 0be66829-03f5-4944-8782-65f4129a73b0
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Velocity

		annotation SummarizationSetBy = User

	column 'Draw Number'
		dataType: int64
		formatString: 0
		lineageTag: eb89837b-ba9f-40db-bfcf-aa5940a0b284
		sourceLineageTag: 8870aea4-8c3d-4647-be84-8be801f23d13
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Draw Number

		annotation SummarizationSetBy = User

	column 'Entry Number'
		dataType: int64
		formatString: 0
		lineageTag: 4c66f48e-46e2-452a-9358-da7f713647d0
		sourceLineageTag: 92880bce-0dde-4824-9586-7c76e67adc20
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Entry Number

		annotation SummarizationSetBy = User

	column 'Cumulative Distance'
		dataType: double
		lineageTag: 938e1e99-d5d9-4de7-b691-09e3b40548c2
		sourceLineageTag: 28f5842c-8cef-42e7-9813-dbe164111c9c
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Cumulative Distance

		annotation SummarizationSetBy = User

	column 'Radio Percentage'
		dataType: double
		lineageTag: 25f89bc5-eb97-4811-abd8-8fe462d4091e
		sourceLineageTag: dd630c91-9075-4a3b-948d-760b5b73958b
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Radio Percentage

		annotation SummarizationSetBy = User

	column 'Official Rating'
		dataType: double
		lineageTag: 5fdcf8f9-ea47-496a-aa5a-babc3bfc6f5c
		sourceLineageTag: 52bde8b8-c536-4976-aed9-dfc942148b8e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Official Rating

		annotation SummarizationSetBy = User

	column 'Horse Weight'
		dataType: double
		lineageTag: 82ce1a04-9799-4dbb-873f-efd0cedfece9
		sourceLineageTag: f4bcf63e-c8a0-4f9e-aeb8-6bc37ab11f67
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Horse Weight

		annotation SummarizationSetBy = User

	column 'Jockey Allowance'
		dataType: double
		lineageTag: f6a0f60e-1ec9-4eeb-bc06-3145ef6997ee
		sourceLineageTag: e1bb961f-3be1-4409-ba1c-9a3b0b0fe3ca
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Jockey Allowance

		annotation SummarizationSetBy = User

	column 'Jockey Name'
		dataType: string
		lineageTag: 6f642023-738b-4c94-a7af-c2c189692456
		sourceLineageTag: c9601d52-cf50-4d69-9938-cd78407673c8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Jockey Name

		annotation SummarizationSetBy = User

	column 'Trainer Name'
		dataType: string
		lineageTag: 1cc8e262-25c1-4310-818e-5dd562e845e4
		sourceLineageTag: fadd383b-fd2b-4b03-8538-db6a88e6ef03
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Trainer Name

		annotation SummarizationSetBy = User

	column 'Owner Name'
		dataType: string
		lineageTag: b052fc98-9377-461d-b083-fd56adbfcb72
		sourceLineageTag: 6af53891-c5c6-446c-aad9-a6c7b944384b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Owner Name

		annotation SummarizationSetBy = User

	column 'Finish Line Error'
		dataType: double
		formatString: 0.0000
		lineageTag: 6f10167b-5e02-4712-8ad8-03279b85d4e9
		sourceLineageTag: 8b3e1bff-4488-4abc-98cb-fd68d913c2fe
		dataCategory: Uncategorized
		summarizeBy: average
		sourceColumn: Finish Line Error

		annotation SummarizationSetBy = User

	column 'Absolute Finish Line Error'
		dataType: double
		formatString: 0.0000
		lineageTag: 40763986-94c6-4070-bddf-7abe60d6f844
		sourceLineageTag: f93a7a8b-3f71-42fa-aed8-35faafe73a54
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Absolute Finish Line Error

		annotation SummarizationSetBy = User

	partition 'TPD Runner' = entity
		mode: directQuery
		source
			entityName: TPD Runner
			expressionSource: 'DirectQuery to AS - _source'

	annotation PBI_ResultType = Exception

